"""composition entities (P8)

Revision ID: 4040fb150042
Revises: f9cb963715a8
Create Date: 2026-10-03 20:58:51.245085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4040fb150042'
down_revision: Union[str, Sequence[str], None] = 'f9cb963715a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_dependencies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'component_id', 'depends_on', name='uq_dep')
    )
    with op.batch_alter_table('component_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_dependencies_chain_id'), ['chain_id'], unique=False)

    op.create_table('composition_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('composition_validations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=True),
    sa.Column('spec_hash', sa.String(length=64), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('adapters_used', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('composition_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_composition_validations_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_composition_validations_spec_hash'), ['spec_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_composition_validations_spec_hash'))
        batch_op.drop_index(batch_op.f('ix_composition_validations_chain_id'))

    op.drop_table('composition_validations')
    op.drop_table('composition_templates')
    with op.batch_alter_table('component_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_dependencies_chain_id'))

    op.drop_table('component_dependencies')
    # ### end Alembic commands ###
