"""topology entities (P11)

Revision ID: 7b6b540f5991
Revises: 4040fb150042
Create Date: 2026-10-03 21:24:09.914799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6b540f5991'
down_revision: Union[str, Sequence[str], None] = '4040fb150042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topologies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topology_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('topology_id', sa.String(length=32), nullable=False),
    sa.Column('edge_id', sa.String(length=64), nullable=False),
    sa.Column('from_node', sa.String(length=32), nullable=False),
    sa.Column('to_node', sa.String(length=32), nullable=False),
    sa.Column('route', sa.String(length=120), nullable=False),
    sa.Column('route_kind', sa.String(length=8), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('verification', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topology_id', 'edge_id', name='uq_topo_edge')
    )
    op.create_table('topology_paths',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('topology_id', sa.String(length=32), nullable=False),
    sa.Column('path_id', sa.String(length=64), nullable=False),
    sa.Column('edge_ids', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('topology_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topology_revisions')
    op.drop_table('topology_paths')
    op.drop_table('topology_edges')
    op.drop_table('topologies')
    # ### end Alembic commands ###
