"""initial canonical schema (P2)

Revision ID: f9cb963715a8
Revises: 
Create Date: 2026-10-03 20:00:36.889759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cb963715a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_telegram', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_kind'), ['kind'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    op.create_table('chains',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('maturity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_manifests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_manifests_engine_id'), ['engine_id'], unique=False)

    op.create_table('engines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('implementation_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)

    op.create_table('failover_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('preemption', sa.String(length=16), nullable=False),
    sa.Column('health_policy', sa.JSON(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('recovery_threshold', sa.Integer(), nullable=False),
    sa.Column('cooldown_s', sa.Integer(), nullable=False),
    sa.Column('hysteresis_margin', sa.Float(), nullable=False),
    sa.Column('max_switches_per_window', sa.Integer(), nullable=False),
    sa.Column('maintenance', sa.Boolean(), nullable=False),
    sa.Column('pinned_member', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('health_samples',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate', sa.String(length=120), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('rtt_ms', sa.Float(), nullable=True),
    sa.Column('jitter_ms', sa.Float(), nullable=True),
    sa.Column('loss_pct', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_samples_candidate'), ['candidate'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_samples_ts'), ['ts'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_username', sa.String(length=64), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('secret_ref', sa.String(length=64), nullable=True),
    sa.Column('host_key_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('sudo_mode', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('agent_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('secret_references',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('cipher', sa.String(length=32), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('node_a', sa.String(length=32), nullable=False),
    sa.Column('node_b', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=8), nullable=False),
    sa.Column('methodology', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_a'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['node_b'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_components',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=True),
    sa.Column('legacy_method_id', sa.String(length=64), nullable=True),
    sa.Column('node_a', sa.String(length=32), nullable=True),
    sa.Column('node_b', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'component_id', name='uq_chain_component')
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=True),
    sa.Column('node_a', sa.String(length=32), nullable=False),
    sa.Column('node_b', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('desired_state', sa.JSON(), nullable=False),
    sa.Column('plan_preview', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_a'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['node_b'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('legacy_method_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('implementation_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_id', 'profile_id', name='uq_engine_profile'),
    sa.UniqueConstraint('legacy_method_id')
    )
    op.create_table('node_inventories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_samples',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('candidate', sa.String(length=120), nullable=False),
    sa.Column('candidate_kind', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'candidate', name='uq_run_candidate')
    )
    op.create_table('deployment_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('deployment_id', sa.String(length=32), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('desired_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failover_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('candidate', sa.String(length=120), nullable=False),
    sa.Column('candidate_kind', sa.String(length=8), nullable=False),
    sa.Column('deployment_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['failover_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'priority', name='uq_member_priority')
    )
    op.create_table('method_verifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['engine_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_allocations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('deployment_id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=True),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('node_id', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # live-row uniqueness only (partial index; released rows remain as history)
    op.create_index('uq_resource_live', 'resource_allocations',
                    ['kind', 'key', 'node_id'], unique=True,
                    postgresql_where=sa.text('released_at IS NULL'),
                    sqlite_where=sa.text('released_at IS NULL'))
    op.create_table('scores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate', sa.String(length=120), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['benchmark_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_candidate'), ['candidate'], unique=False)

    op.create_table('benchmark_receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sample_id', sa.String(length=32), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['benchmark_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmark_receipts')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_candidate'))

    op.drop_table('scores')
    op.drop_table('resource_allocations')
    op.drop_table('method_verifications')
    op.drop_table('failover_members')
    op.drop_table('deployment_revisions')
    op.drop_table('benchmark_samples')
    op.drop_table('node_inventories')
    op.drop_table('engine_profiles')
    op.drop_table('deployments')
    op.drop_table('chain_components')
    op.drop_table('benchmark_runs')
    op.drop_table('secret_references')
    op.drop_table('nodes')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('health_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_samples_ts'))
        batch_op.drop_index(batch_op.f('ix_health_samples_candidate'))

    op.drop_table('health_samples')
    op.drop_table('failover_groups')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_ts'))

    op.drop_table('events')
    op.drop_table('engines')
    with op.batch_alter_table('engine_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_manifests_engine_id'))

    op.drop_table('engine_manifests')
    op.drop_table('chains')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_kind'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
