#!/usr/bin/env python3
"""One-shot generator for engines/manifests/*.json (P3).

Run once to emit the 22 engine manifests; the JSON files are the committed
source of truth afterwards. Every document satisfies engines.manifests.validate.
"""
import json
import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parents[1] / "engines" / "manifests"

L3I, L2I, TUN, TAP = "L3_INTERFACE", "L2_INTERFACE", "TUN_INTERFACE", "TAP_INTERFACE"
TCP, UDP, SOCKS, HTTP = "TCP_STREAM", "UDP_DATAGRAM", "SOCKS5_PROXY", "HTTP_PROXY"
RAWIP, P41, P47, IPSEC = "RAW_IP", "IP_PROTOCOL_41", "IP_PROTOCOL_47", "IPSEC"
RTCP, RUDP, QUIC, TLS = "REVERSE_TCP", "REVERSE_UDP", "QUIC", "TLS"

M = {
 "wireguard": dict(name="WireGuard", family="vpn", version="1.0", maturity="STANDARD",
   layer="L3", transport=["udp"], requires=[UDP], provides=[L3I, TUN],
   required_binaries=["wg", "wg-quick"], required_kernel_modules=["wireguard"],
   required_privileges="CAP_NET_ADMIN", ports={"udp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=True, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="ChaCha20-Poly1305", mtu_overhead=80,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["needs kernel >= 5.6 or DKMS"],
   verification="REAL_PAIR_VERIFIED"),
 "gre": dict(name="GRE", family="kernel", version="1.0", maturity="STANDARD",
   layer="L3", transport=["ip"], requires=[RAWIP], provides=[L3I, RAWIP],
   required_binaries=["ip"], required_kernel_modules=["ip_gre"],
   required_privileges="CAP_NET_ADMIN", ports={}, ip_protocols=[47],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=True, encryption="none", mtu_overhead=24,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["no encryption by itself"],
   verification="REAL_PAIR_VERIFIED"),
 "gretap": dict(name="GRETAP", family="kernel", version="1.0", maturity="STANDARD",
   layer="L2", transport=["ethernet"], requires=[RAWIP], provides=[L2I, TAP],
   required_binaries=["ip"], required_kernel_modules=["ip_gre"],
   required_privileges="CAP_NET_ADMIN", ports={}, ip_protocols=[47],
   ipv4=True, ipv6=False, tun=False, tap=True, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="none", mtu_overhead=38,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["bridging requires care on some distros"],
   verification="REAL_PAIR_VERIFIED"),
 "ipip": dict(name="IPIP", family="kernel", version="1.0", maturity="STANDARD",
   layer="L3", transport=["ip"], requires=[RAWIP], provides=[L3I],
   required_binaries=["ip"], required_kernel_modules=["ipip"],
   required_privileges="CAP_NET_ADMIN", ports={}, ip_protocols=[4],
   ipv4=True, ipv6=False, tun=False, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="none", mtu_overhead=20,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["IPv4 only; no encryption"],
   verification="REAL_PAIR_VERIFIED"),
 "sit": dict(name="SIT / 6in4", family="kernel", version="1.0", maturity="STANDARD",
   layer="L3", transport=["ip"], requires=[RAWIP], provides=[L3I],
   required_binaries=["ip"], required_kernel_modules=["sit"],
   required_privileges="CAP_NET_ADMIN", ports={}, ip_protocols=[41],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="none", mtu_overhead=20,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["carries IPv6 inside IPv4; no encryption"],
   verification="REAL_PAIR_VERIFIED"),
 "vti": dict(name="VTI (IPsec)", family="vpn", version="1.0", maturity="ADVANCED",
   layer="L3", transport=["ip"], requires=[RAWIP], provides=[L3I, TUN],
   required_binaries=["ip", "swanctl"], required_kernel_modules=["vti", "xfrm"],
   required_privileges="CAP_NET_ADMIN", ports={"udp": [500, 4500]}, ip_protocols=[50, 51],
   ipv4=True, ipv6=True, tun=True, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="IPsec ESP (AES-GCM)", mtu_overhead=70,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=False,
   known_limitations=["requires strongSwan IKE on both ends"],
   verification="REAL_PAIR_VERIFIED"),
 "vxlan": dict(name="VXLAN", family="kernel", version="1.0", maturity="STANDARD",
   layer="L2", transport=["udp"], requires=[UDP], provides=[L2I, TAP],
   required_binaries=["ip"], required_kernel_modules=["vxlan"],
   required_privileges="CAP_NET_ADMIN", ports={"udp": 4789}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=True, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="none", mtu_overhead=50,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["default port 4789 must be open"],
   verification="REAL_PAIR_VERIFIED"),
 "openvpn": dict(name="OpenVPN", family="vpn", version="2.6", maturity="STANDARD",
   layer="L3", transport=["tcp", "udp"], requires=[TCP, UDP], provides=[L3I, TUN],
   required_binaries=["openvpn"], required_kernel_modules=["tun"],
   required_privileges="CAP_NET_ADMIN", ports={"udp": "any", "tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=True, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="AES-256-GCM / TLS", mtu_overhead=70,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=False,
   known_limitations=["higher CPU than WireGuard at same throughput"],
   verification="REAL_PAIR_VERIFIED"),
 "ipsec": dict(name="IPsec/IKEv2/L2TP", family="vpn", version="1.0", maturity="ADVANCED",
   layer="L3", transport=["ip"], requires=[RAWIP], provides=[L3I, TUN, IPSEC],
   required_binaries=["swanctl", "ip"], required_kernel_modules=["xfrm", "esp"],
   required_privileges="CAP_NET_ADMIN", ports={"udp": [500, 4500]}, ip_protocols=[50, 51],
   ipv4=True, ipv6=True, tun=True, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="IPsec ESP", mtu_overhead=70,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=False, repeatable=False,
   known_limitations=["IKE daemon config complexity"],
   verification="REAL_PAIR_VERIFIED"),
 "ssh": dict(name="SSH forwarding/tun", family="proxy", version="1.0", maturity="STANDARD",
   layer="L4", transport=["tcp"], requires=[TCP], provides=[TCP, SOCKS, RTCP, TUN, TAP],
   required_binaries=["ssh"], required_kernel_modules=[],
   required_privileges="none (tun profiles need root)", ports={"tcp": 22}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=True, tap=True, socks=True, http_proxy=False,
   reverse=True, raw_ip=False, encryption="SSH ChaCha20/AES", mtu_overhead=40,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["per-connection TCP overhead; tun profiles need PermitTun"],
   verification="REAL_PAIR_VERIFIED"),
 "gost": dict(name="GOST", family="proxy", version="3.0", maturity="STANDARD",
   layer="L4", transport=["tcp", "udp"], requires=[TCP, UDP],
   provides=[TCP, UDP, SOCKS, HTTP, TUN, TAP, RTCP, RUDP, TLS, QUIC],
   required_binaries=["gost"], required_kernel_modules=[],
   required_privileges="none (tun/tap profiles need CAP_NET_ADMIN)",
   ports={"tcp": "any", "udp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=True, tap=True, socks=True, http_proxy=True,
   reverse=True, raw_ip=False, encryption="TLS optional", mtu_overhead=15,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["15 profiles differ in transport; tun/tap profiles need root"],
   verification="REAL_PAIR_VERIFIED"),
 "xray": dict(name="Xray (VLESS)", family="proxy", version="25.x", maturity="STANDARD",
   layer="L4", transport=["tcp"], requires=[TCP], provides=[TCP, SOCKS, TLS, QUIC],
   required_binaries=["xray"], required_kernel_modules=[],
   required_privileges="none", ports={"tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=True, http_proxy=False,
   reverse=False, raw_ip=False, encryption="REALITY/TLS optional", mtu_overhead=10,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["carrier-class proxy: needs a real peer for full verification"],
   verification="REAL_PAIR_VERIFIED"),
 "singbox": dict(name="sing-box", family="proxy", version="1.x", maturity="STANDARD",
   layer="L4", transport=["tcp", "udp", "quic"], requires=[TCP, UDP],
   provides=[TCP, UDP, SOCKS, TUN, TLS, QUIC],
   required_binaries=["sing-box"], required_kernel_modules=[],
   required_privileges="none (tun profile needs CAP_NET_ADMIN)",
   ports={"tcp": "any", "udp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=True, tap=False, socks=True, http_proxy=False,
   reverse=False, raw_ip=False, encryption="protocol-dependent", mtu_overhead=20,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["tun profile needs root; protocol matrix is wide"],
   verification="REAL_PAIR_VERIFIED"),
 "frp": dict(name="FRP", family="forwarder", version="0.6x", maturity="STANDARD",
   layer="L4", transport=["tcp", "udp", "quic"], requires=[TCP, UDP],
   provides=[TCP, UDP, RTCP, RUDP, TLS, QUIC],
   required_binaries=["frpc", "frps"], required_kernel_modules=[],
   required_privileges="none", ports={"tcp": 7000, "udp": 7000}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=False, http_proxy=False,
   reverse=True, raw_ip=False, encryption="TLS optional", mtu_overhead=10,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["server/client roles must be provisioned as a pair"],
   verification="REAL_PAIR_VERIFIED"),
 "rathole": dict(name="rathole", family="forwarder", version="0.5", maturity="STANDARD",
   layer="L4", transport=["tcp"], requires=[TCP], provides=[TCP, RTCP, TLS],
   required_binaries=["rathole"], required_kernel_modules=[],
   required_privileges="none", ports={"tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=False, http_proxy=False,
   reverse=True, raw_ip=False, encryption="Noise/TLS", mtu_overhead=10,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["TCP-oriented; UDP support is limited"],
   verification="REAL_PAIR_VERIFIED"),
 "chisel": dict(name="chisel", family="forwarder", version="1.x", maturity="STANDARD",
   layer="L4", transport=["tcp"], requires=[TCP], provides=[TCP, SOCKS, RTCP, RUDP, TLS],
   required_binaries=["chisel"], required_kernel_modules=[],
   required_privileges="none", ports={"tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=True, http_proxy=False,
   reverse=True, raw_ip=False, encryption="TLS + auth", mtu_overhead=10,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["HTTP-based: long-lived connections may be proxied by CDNs"],
   verification="REAL_PAIR_VERIFIED"),
 "wstunnel": dict(name="wstunnel", family="forwarder", version="2.x", maturity="STANDARD",
   layer="L4", transport=["tcp"], requires=[TCP], provides=[TCP, UDP, SOCKS, TLS],
   required_binaries=["wstunnel"], required_kernel_modules=[],
   required_privileges="none", ports={"tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=True, http_proxy=False,
   reverse=False, raw_ip=False, encryption="wss/TLS", mtu_overhead=10,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["UDP-over-WS adds overhead and jitter"],
   verification="REAL_PAIR_VERIFIED"),
 "waterwall": dict(name="WaterWall", family="proxy", version="1.x", maturity="EXPERIMENTAL",
   layer="L4", transport=["tcp"], requires=[TCP], provides=[TCP, RTCP, TLS],
   required_binaries=["waterwall"], required_kernel_modules=[],
   required_privileges="none", ports={"tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=True, tun=False, tap=False, socks=False, http_proxy=False,
   reverse=True, raw_ip=False, encryption="TLS optional", mtu_overhead=10,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["config-driven; fewer distro packages"],
   verification="LAB_VERIFIED"),
 "paqet": dict(name="PAQET", family="custom", version="1.x", maturity="EXPERIMENTAL",
   layer="L4", transport=["tcp", "udp"], requires=[TCP, UDP], provides=[TCP, UDP, SOCKS],
   required_binaries=["paqet"], required_kernel_modules=[],
   required_privileges="root (raw socket modes)", ports={"tcp": "any", "udp": "any"},
   ip_protocols=[], ipv4=True, ipv6=False, tun=False, tap=False, socks=True,
   http_proxy=False, reverse=False, raw_ip=False, encryption="custom",
   mtu_overhead=10, can_be_overlay=True, can_be_underlay=True, can_be_nested=True,
   repeatable=True, known_limitations=["needs NOTRACK iptables rules; root required"],
   verification="LAB_VERIFIED"),
 "hedioum": dict(name="Hedioum", family="custom", version="1.x", maturity="EXPERIMENTAL",
   layer="L3", transport=["tcp"], requires=[TCP], provides=[L3I, TUN, SOCKS],
   required_binaries=["hedioum"], required_kernel_modules=["tun"],
   required_privileges="CAP_NET_ADMIN", ports={"tcp": "any"}, ip_protocols=[],
   ipv4=True, ipv6=False, tun=True, tap=False, socks=True, http_proxy=False,
   reverse=False, raw_ip=False, encryption="custom", mtu_overhead=60,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["pairing-token flow; pool_socks profile differs"],
   verification="LAB_VERIFIED"),
 "hajsaman": dict(name="HajSaman", family="custom", version="1.x", maturity="EXPERIMENTAL",
   layer="L3", transport=["ip"], requires=[RAWIP], provides=[L3I, TUN],
   required_binaries=["hajsaman"], required_kernel_modules=["sit", "wireguard"],
   required_privileges="CAP_NET_ADMIN", ports={"udp": "any"}, ip_protocols=[41],
   ipv4=True, ipv6=True, tun=True, tap=False, socks=False, http_proxy=False,
   reverse=False, raw_ip=False, encryption="slot-dependent", mtu_overhead=40,
   can_be_overlay=True, can_be_underlay=True, can_be_nested=True, repeatable=True,
   known_limitations=["slot-based custom transport"],
   verification="LAB_VERIFIED"),
}


def main() -> int:
    sys.path.insert(0, str(OUT.parent.parent))
    from engines.manifests import validate
    for eid, m in M.items():
        doc = {"id": eid, **m}
        doc.setdefault("supported_os", ["linux"])
        doc.setdefault("supported_arch", ["amd64", "arm64"])
        doc.setdefault("implementation_status", "IMPLEMENTED")
        validate(doc)  # fail fast before writing
        (OUT / f"{eid}.json").write_text(
            json.dumps(doc, indent=2, sort_keys=False) + "\n", encoding="utf-8", newline="\n")
        print("wrote", eid + ".json")
    print(f"{len(M)} manifests generated and validated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
