#!/usr/bin/env python3
"""Generate docs/development/CATALOG_INVENTORY.md — machine-generated method-ID
inventory across the three generations (P1.6).

Sources (all parsed statically, no imports of the apps themselves):
  Gen1a  backend/app/tunnel_catalog.py      (CATALOG + EXTRA_METHODS + PACK3_METHODS)
  Gen1b  plan_executor/executor.py          (SUPPORTED set, AST-parsed)
  Gen2   deploy/methods_registry.json       (82-entry MTF registry)
  Gen3   tunnelguard/tfd/engines/           (adapter ENGINE ids)

Run:  python scripts/generate_catalog_inventory.py
"""
from __future__ import annotations

import ast
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/development/CATALOG_INVENTORY.md"


def gen1_catalog() -> dict[str, str]:
    """method_id -> family, from backend catalog list-of-dicts."""
    src = (ROOT / "backend/app/tunnel_catalog.py").read_text(encoding="utf-8")
    env: dict = {}
    exec(compile(src, "tunnel_catalog.py", "exec"), env)  # static data module, no app deps
    out: dict[str, str] = {}
    for block in ("CATALOG", "EXTRA_METHODS", "PACK3_METHODS"):
        for entry in env.get(block, []):
            mid = entry.get("id")
            if mid:
                out[mid] = str(entry.get("family") or entry.get("set") or "?")
    return out


def gen1_executor() -> set[str]:
    tree = ast.parse((ROOT / "plan_executor/executor.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "SUPPORTED" for t in node.targets
        ):
            return set(ast.literal_eval(node.value))
    return set()


def gen2_registry() -> dict[str, dict]:
    reg = json.loads((ROOT / "deploy/methods_registry.json").read_text(encoding="utf-8"))
    methods = reg["methods"] if isinstance(reg, dict) else reg
    return {m["id"]: m for m in methods}


def gen3_engines() -> set[str]:
    ids = set()
    eng_dir = ROOT / "tunnelguard/tfd/engines"
    for py in eng_dir.glob("*.py"):
        src = py.read_text(encoding="utf-8")
        # adapter classes declare `name = "<engine>"` as a class attribute
        ids.update(re.findall(r"^\s{4}name = \"([a-z0-9_]+)\"", src, re.M))
    return {i.upper() for i in ids}


def family_of(mid: str, reg: dict[str, dict]) -> str:
    m = reg.get(mid)
    if m:
        return str(m.get("set") or m.get("family") or "?").replace("_METHODS", "")
    if mid.startswith("GOST"):
        return "GOST"
    if mid.startswith("VLESS") or mid.startswith("XRAY"):
        return "XRAY"
    if mid.startswith("SSH") or mid.startswith("AUTOSSH"):
        return "SSH"
    if mid.startswith("FRP"):
        return "FRP"
    if mid.startswith("RATHOLE"):
        return "RATHOLE"
    if mid.startswith("CHISEL"):
        return "CHISEL"
    if mid.startswith("WSTUNNEL"):
        return "WSTUNNEL"
    if mid.startswith("WATERWALL"):
        return "WATERWALL"
    if mid.startswith("PAQET"):
        return "PAQET"
    if mid.startswith("SINGBOX"):
        return "SINGBOX"
    if mid.startswith("HEDIOUM"):
        return "HEDIOUM"
    if mid.startswith("HAJSAMAN"):
        return "HAJSAMAN"
    if "OVER" in mid:
        return "COMPOSITE"
    if mid in {"WIREGUARD", "GRE", "GRETAP", "IPIP", "SIT_6IN4", "VTI", "VTI6",
               "VXLAN", "IP6GRE", "IP6GRETAP", "L2TP_IPSEC", "IKEV2_IPSEC", "OPENVPN"}:
        return "KERNEL/VPN"
    return "?"


def main() -> int:
    cat = gen1_catalog()
    exe = gen1_executor()
    reg = gen2_registry()
    tg = gen3_engines()

    all_ids = sorted(set(cat) | exe | set(reg) | tg)

    lines = [
        "# CATALOG INVENTORY — machine-generated cross-generation method map (P1.6)",
        "",
        "Generated by `scripts/generate_catalog_inventory.py` — do not edit by hand.",
        "",
        f"- Gen1 backend catalog (`backend/app/tunnel_catalog.py`): **{len(cat)}**",
        f"- Gen1 executor SUPPORTED (`plan_executor/executor.py`): **{len(exe)}**",
        f"- Gen2 MTF registry (`deploy/methods_registry.json`): **{len(reg)}**",
        f"- Gen3 TunnelGuard engines (`tunnelguard/tfd/engines/`): **{len(tg)}** → "
        + ", ".join(f"`{i}`" for i in sorted(tg)),
        f"- **Union of all method IDs: {len(all_ids)}**",
        "",
        "Legend: G1c = Gen1 catalog · G1e = Gen1 executor · G2 = Gen2 registry · G3 = Gen3 engine adapter.",
        "impl = real persistent-deploy implementation (Gen1 executor) · harness = MTF test harness ·"
        " adapter = TunnelGuard engine adapter.",
        "",
        "| method_id | family | G1c | G1e | G2 | G3 | impl location(s) |",
        "|---|---|---|---|---|---|---|",
    ]
    for mid in all_ids:
        fam = family_of(mid, reg)
        locs = []
        if mid in exe:
            locs.append("executor.py")
        if mid in reg:
            locs.append("mtf harness")
        if mid in tg:
            locs.append("tfd adapter")
        if mid in cat and mid not in exe and mid not in reg:
            locs.append("catalog-only")
        lines.append(
            f"| `{mid}` | {fam} | {'✓' if mid in cat else '—'} | {'✓' if mid in exe else '—'} "
            f"| {'✓' if mid in reg else '—'} | {'✓' if mid in tg else '—'} | {', '.join(locs) or '—'} |"
        )

    only_cat = sorted(set(cat) - exe - set(reg))
    only_exe = sorted(exe - set(cat))
    only_reg = sorted(set(reg) - set(cat) - exe)
    cat_exe_diff = sorted(set(cat) ^ exe)
    lines += [
        "",
        "## Drift analysis",
        "",
        f"- catalog ↔ executor symmetric difference: **{len(cat_exe_diff)}**"
        + (f" → {', '.join(f'`{m}`' for m in cat_exe_diff)}" if cat_exe_diff else ""),
        f"- in catalog but neither executor nor registry: **{len(only_cat)}**"
        + (f" → {', '.join(f'`{m}`' for m in only_cat)}" if only_cat else ""),
        f"- in executor but not catalog: **{len(only_exe)}**"
        + (f" → {', '.join(f'`{m}`' for m in only_exe)}" if only_exe else ""),
        f"- in registry only (test-harness flagships): **{len(only_reg)}**"
        + (f" → {', '.join(f'`{m}`' for m in only_reg)}" if only_reg else ""),
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(all_ids)} ids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
