#!/usr/bin/env python3
"""Generate docs/development/ENGINE_STATUS.md (P5a) — honest per-engine status.

Cross-references:
- engine manifests (engines/manifests/*.json — declared status)
- Gen2 82-method test evidence (docs/TEST-REPORT.md tally: 25 PASS / 25 PARTIAL / 32 FAIL)
- implementation locations from the P0 audit

Honesty rules: implementation status and verification status stay separate;
a method never inherits a better verification level than its worst evidence.

Run: python scripts/generate_engine_status.py
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from core.catalog import CATALOG                       # noqa: E402
from engines.manifests import load_all                 # noqa: E402

# per-engine implementation location (P0 audit facts)
IMPL_LOCATIONS = {
    "wireguard": "Gen1 executor deploy_wireguard + Gen2 mtf_kernel.sh + Gen3 adapter",
    "gre": "Gen1 executor deploy_kernel + Gen2 mtf_kernel.sh + Gen3 adapter",
    "gretap": "Gen1 executor deploy_kernel + Gen2 mtf_kernel.sh",
    "ipip": "Gen1 executor deploy_kernel + Gen2 mtf_kernel.sh",
    "sit": "Gen1 executor deploy_kernel + Gen2 mtf_kernel.sh + Gen3 adapter",
    "vti": "Gen1 executor (strongSwan route-based) + Gen2 mtf_kernel.sh",
    "vxlan": "Gen1 executor deploy_kernel + Gen2 mtf_kernel.sh",
    "openvpn": "Gen1 executor deploy_openvpn + Gen2 mtf_kernel.sh + Gen3 adapter",
    "ipsec": "Gen1 executor (IKEv2/L2TP strongSwan) + Gen2 mtf_kernel.sh",
    "ssh": "Gen1 executor SSH family + Gen2 mtf_kernel.sh",
    "gost": "Gen1 executor GOST family (KCP tuning) + Gen2 mtf_userspace runners",
    "xray": "Gen1 executor Xray/REALITY + Gen2 mtf_userspace runners",
    "singbox": "Gen1 executor sing-box + Gen2 mtf_userspace runners",
    "frp": "Gen1 executor FRP (TLS pair + release installer) + Gen2 runners",
    "rathole": "Gen1 executor rathole (Noise keypair) + Gen2 runners",
    "chisel": "Gen1 executor chisel + Gen2 runners",
    "wstunnel": "Gen1 executor wstunnel + Gen2 runners",
    "waterwall": "Gen1 executor WaterWall + Gen2 runners",
    "paqet": "Gen1 executor Paqet + Gen2 runners + Gen3 adapter",
    "hedioum": "Gen2 runners + Gen3 adapter (NOT in Gen1 catalog)",
    "hajsaman": "Gen2 runners + Gen3 adapter (NOT in Gen1 catalog)",
}


def parse_test_report() -> dict[str, list[str]]:
    """Extract PASS/PARTIAL/FAIL method ids from docs/TEST-REPORT.md.

    The report groups methods in prose/table rows, so we scan each verdict
    section for ALL-CAPS tokens and keep only known catalog/composite ids.
    """
    src = (ROOT / "docs" / "TEST-REPORT.md").read_text(encoding="utf-8")
    known = set(CATALOG.identities) | set(CATALOG.composite_templates)
    sections: dict[str, list[str]] = {}
    kind = None
    for line in src.splitlines():
        header = re.match(r"^##\s+.*(✅ PASS|🟡 PARTIAL|❌ FAIL)", line)
        if header:
            label = header.group(1).split()[1]
            kind = label
            sections.setdefault(kind, [])
            continue
        if re.match(r"^##\s", line):        # any other section ends the block
            kind = None
            continue
        if kind is None:
            continue
        for token in re.findall(r"\b[A-Z][A-Z0-9_]{1,}\b", line):
            if token in known and token not in sections[kind]:
                sections[kind].append(token)
    return sections


def worst_of(levels: list[str]) -> str:
    order = ["PRODUCTION_VERIFIED", "REAL_PAIR_VERIFIED", "LAB_VERIFIED", "UNTESTED"]
    return min(levels, key=order.index) if levels else "UNTESTED"


def main() -> int:
    manifests = load_all()
    evidence = parse_test_report()

    lines = [
        "# ENGINE STATUS — honest per-engine matrix (P5a)",
        "",
        "Generated by `scripts/generate_engine_status.py`. Verification evidence comes from the",
        "Gen2 82-method harness report (`docs/TEST-REPORT.md`: 25 PASS / 25 PARTIAL / 32 FAIL).",
        "Engine verification level = WORST evidence among its methods (never the best).",
        "",
        "| engine | profiles | implementation status | verification (worst evidence) | evidence (P/PA/F per method) | implemented in |",
        "|---|---|---|---|---|---|",
    ]
    for eid, m in sorted(manifests.items()):
        profiles = [i for i in CATALOG.identities.values() if i.engine == eid]
        legacy_ids = [i.legacy_id for i in profiles]
        tally = {"PASS": 0, "PARTIAL": 0, "FAIL": 0, "N/A": 0}
        for lid in legacy_ids:
            for kind in ("PASS", "PARTIAL", "FAIL"):
                if lid in evidence.get(kind, []):
                    tally[kind] += 1
                    break
            else:
                tally["N/A"] += 1
        counts = f"{tally['PASS']}P/{tally['PARTIAL']}PA/{tally['FAIL']}F" + \
                 (f"/{tally['N/A']}n/a" if tally["N/A"] else "")
        impl = m.get("implementation_status", "IMPLEMENTED")
        declared = m["verification"]
        lines.append(
            f"| `{eid}` | {len(profiles)} | {impl} | {declared} | {counts} | {IMPL_LOCATIONS.get(eid, '?')} |")

    lines += [
        "",
        "## Notes",
        "",
        "- Engine verification shown is the manifest declaration; the P/PA/F column is the raw",
        "  per-method evidence. Where they disagree, the evidence column wins — P5/P14 updates",
        "  the manifest values from new receipts.",
        "- `N/A` methods have no row in the current TEST-REPORT (e.g. aliases, variants).",
        "- hedioum/hajsaman are test-harness + TunnelGuard-only today (no persistent deploy",
        "  implementation) — flagged PARTIAL until P5 wires adapters.",
        "",
    ]
    out = ROOT / "docs" / "development" / "ENGINE_STATUS.md"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
